apiVersion: v1
kind: ConfigMap
metadata:
  name: income-config
data:
  LOG_LEVEL: "INFO"
  MODEL_PATH: models/baseline_logreg.joblib
  MLFLOW_TRACKING_URI: http://mlflow.mlops:5000
  MODEL_NAME: income
  MODEL_ALIAS: champion