apiVersion: v1
kind: Service
metadata:
  name: income-service
  labels:
    app: income
spec:
  type: ClusterIP
  selector:
    app: income
  ports:
    - name: http
      port: 80
      targetPort: 8000
